services:
    vesax.seo.doctrine_rules_repository:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine.orm.entity_manager", "getRepository"]
        arguments:
            - Vesax\SEOBundle\Entity\Rule

    vesax.seo.redirect_rule_repository:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine.orm.entity_manager", "getRepository"]
        arguments:
            - Vesax\SEOBundle\Entity\RedirectRule

    vesax.seo.rules_provider_doctrine:
        class: Vesax\SEOBundle\Rule\DoctrineRulesProvider
        arguments:
            - @vesax.seo.doctrine_rules_repository

    vesax.seo.compiler:
        class: Vesax\SEOBundle\Metadata\Compiler\Compiler
        arguments:
            - @twig

    vesax.seo.metadata_factory:
        class: Vesax\SEOBundle\Metadata\MetadataFactory
        arguments:
            - @vesax.seo.rules_provider_doctrine
            - @vesax.seo.compiler
            - @?vesax.seo.metadata_cache

    vesax.seo.twig_extension:
        class: Vesax\SEOBundle\Twig\Extension\SEOExtension
        arguments:
            - @vesax.seo.metadata_factory
            - @request_stack
        tags:
            - { name: twig.extension }